---
title: "rough_work"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r}
library(ggplot2)
```

## Project 1

## First Explanatory of the data

```{r, clean data} 
setwd("~/Google Drive/EPFL/Applied Stat/StatApp-314577/Project-1")
data <- read.csv2("1_snow_particles.csv", sep=",")
data <- data.frame(startpoint <- as.numeric(data$startpoint),
                   endpoint <- as.numeric(data$endpoint),
                   value <- as.numeric(data$retained....),
                   number <- as.numeric(data$particles.detected))
```

```{r, first explanotory}
x <- (data$endpoint-data$startpoint)/2 + data$startpoint
data_clean <- data.frame(start=data$startpoint)

# I plot the proportion in the middle of each innterval 
ggplot()+
  geom_point(aes(x[1:51], data$value[1:51]), color="red")+
  geom_line(aes(x[1:51], data$value[1:51]), color="black")+
  xlab("Diameters")+
  ylab("Proportion")+
  ggtitle("Representation of the 'snow_particles' data ")+
  theme_minimal()

```


```{r}
# I would like to create an approximation of the density by taking the length of the interval into account 

length_inter <- (data$endpoint - data$startpoint)*100


ggplot()+
  geom_point(aes(x[1:51], data$value[1:51]/length_inter[1:51]), color="red")+
  geom_line(aes(x[1:51], data$value[1:51]/length_inter[1:51]), color="black")+
  xlab("Diameters")+
  ylab("Proportion")+
  ggtitle("Approximation of the density of the 'snow_particles' data")+
  theme_minimal()
```


## Expectation - Maximization (EM) Algorithm 


```{r, bi-log-normal law & log likelihood}
f <- function(x, mu1, mu2, sigma1, sigma2, tau){
  return((1 - tau) * dlnorm(x, mu1, sigma1) + tau * dlnorm(x, mu2, sigma2))
}

log_likelihood <- function(X, mu1, mu2, sigma1, sigma2, tau){
  return (sum(log(f(X, mu1, mu2, sigma1, sigma2, tau))))
}

```

```{r, eval=FALSE}
f_nor <- function(x, mu, sigma){
  return(exp(- (log(x) - mu)^2 / (2 * sigma^2)) / (x * sqrt(2 * pi * sigma^2)))
}

f <- function(x, mu1, mu2, sigma1, sigma2, tau){
  return((1 - tau) * exp(- (log(x) - mu1)^2 / (2 * sigma1^2)) / (x * sqrt(2 * pi * sigma1^2))
         + tau * exp(- (log(x) - mu2)^2 / (2 * sigma2^2)) / (x * sqrt(2 * pi * sigma2^2)))
}

# Other possibility :
f2 <- function(x, mu1, mu2, sigma1, sigma2, tau){
  return((1 - tau) * dnorm(log(x), mu1, sigma1)/x 
         + tau * dnorm(log(x), mu2, sigma2)/x )
}

f3 <- function(x, mu, sigma){
  return(exp(- (log(x) - mu)^2 / (2 * sigma^2)) / (x * sqrt(2 * pi * sigma^2)))
}

log_likelihood <- function(X, mu1, mu2, sigma1, sigma2, tau){
  return (sum(log(f2(X, mu1, mu2, sigma1, sigma2, tau))))
}

log_round <- function(nbr, end, start){
  return(sum(nbr*log(plnorm(end) - plnorm(start))))
}

```

### 2) Jittering & Implementation 


```{r, jittering data}
number <- round((data$value * data$number)/100)
data_jit <- rep(0, length(number))
k <- 0
for(i in 1:45){
  data_jit[(k+1) : (k + number[i])] <- runif(number[i], data$startpoint[i], endpoint[i])
  k <- k + number[i]
}

X <- data_jit

seq <- seq(0, 3, 0.01)
ggplot()+
  geom_histogram(aes(data_jit, y=..density..))+
  geom_line(aes(seq, f(seq, -2, -0.39, sqrt(1/5), sqrt(1/8), 0.75)), col="red")
  #geom_line(aes(x[1:51], data$value[1:51]), color="green")

```

---

```{r, eval=FALSE}
em <- function(tol, mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l){
  mu1_t <- c(mu1_l)
  mu2_t <- c(mu2_l)
  sigma1_t <- c(sigma1_l)
  sigma2_t <- c(sigma2_l)
  tau_t <- c(tau_l)
  
  logl_prev <- 0 
  logl <- log_likelihood(X, mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l)
  i <- 0
  while (abs(logl_prev - logl) > tol & i<300) {
    print(abs(logl_prev - logl))
    i <- i+1
    logl_prev <- logl
    p <- tau_l * f_nor(X, mu2_l, sigma2_l) /  f2(X, mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l)
    tau_l <- mean(p)
    tau_t <- c(tau_t, tau_l)
    
    mu1_l <- sum((1-p)*log(X))/sum(1-p)
    mu2_l <- sum(p*log(X))/sum(p)
    mu1_t <- c(mu1_t, mu1_l) 
    mu2_t <- c(mu2_t, mu2_l) 
    
    sigma1_l <- sqrt(sum((1-p)*(log(X) - mu1_l)^2)/sum(1-p))
    sigma2_l <- sqrt(sum(p * (log(X) - mu2_l)^2)/sum(p))
    sigma1_t <- c(sigma1_t, sigma1_l)
    sigma2_t <- c(sigma2_t, sigma2_l)
    
    logl <- log_likelihood(X, mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l)
  }
  
  if (i>99){
    print("the algorithm didn't converge")
  }
  
  if (tau_l < 0.5){
    return(list(mu2_t, mu1_t, sigma2_t, sigma1_t, 1-tau_t))
  }
  return(list(mu1_t, mu2_t, sigma1_t, sigma2_t, tau_t))
}
```


```{r}

em <- function(X, tol, mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l){
  logl_prev <- 0 
  logl <- log_likelihood(X, mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l)
  i <- 0
  while (abs(logl_prev - logl) > tol & i<300) {
    i <- i+1
    logl_prev <- logl
    p <- tau_l * dlnorm(X, mu2_l, sigma2_l) /  f(X, mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l)
    tau_l <- mean(p)
    
    mu1_l <- sum((1-p)*log(X))/sum(1-p)
    mu2_l <- sum(p*log(X))/sum(p)
    
    sigma1_l <- sqrt(sum((1-p)*(log(X) - mu1_l)^2)/sum(1-p))
    sigma2_l <- sqrt(sum(p * (log(X) - mu2_l)^2)/sum(p))
    
    logl <- log_likelihood(X, mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l)
  }
  
  if (i>99){
    print("the algorithm didn't converge")
  }
  
  if (tau_l < 0.5){
    return(list(mu2_l, mu1_l, sigma2_l, sigma1_l, 1-tau_l))
  }
  return(list(mu1_l, mu2_l, sigma1_l, sigma2_l, tau_l))
}

L <- em(X, 0.000001, -2, -0.39, sqrt(1/5), sqrt(1/8), 0.75)

mu1 = unlist(L[1])
mu2 = unlist(L[2])
sigma1 = unlist(L[3])
sigma2 = unlist(L[4])
tau = unlist(L[5])
```

```{r}
seq <- seq(0, 2, 0.01)

ggplot()+
  geom_histogram(aes(data_jit, y=..density..))+
  ggtitle("Histogram of the jittered data")+
  xlab("Diameters")+
  ylab("")+
  geom_line(aes(seq, f(seq, -2, -0.39, sqrt(1/5), sqrt(1/8), 0.75), colour="Initial_Density"))+
  geom_line(aes(seq, f(seq, mu1, mu2, sigma1, sigma2, tau), colour="Density_Obtained"))+
  scale_color_manual(name="", values=c(Initial_Density = "turquoise3", Density_Obtained="hotpink2"))



```



## Optimization

```{r}
log_round <- function(data, par){
  return(sum(-data$value*log(par[5]*(plnorm(data$endpoint, par[2], par[4]) 
                                    - plnorm(data$startpoint, par[2], par[4])) + 
                       (1- par[5])*(plnorm(data$endpoint, par[1], par[3]) 
                                    - plnorm(data$startpoint, par[1], par[3])))))
}

opti <- optim(par=c(mu1, mu2, sigma1, sigma2, tau), log_round, data=data)$par
```

```{r}
ggplot()+
  geom_histogram(aes(data_jit, y=..density..))+
  ggtitle("Histogram of the jittered data")+
  xlab("Diameters")+
  ylab("")+
  geom_line(aes(seq, f(seq, opti[1], opti[2], opti[3], opti[4],opti[5]), colour="Density_Optimized"))+
  geom_line(aes(seq, f(seq, mu1, mu2, sigma1, sigma2, tau), colour="Density_Obtained"))+
  scale_color_manual(name="", values=c(Density_Optimized = "palegreen3", Density_Obtained="hotpink2"))

ggplot()+
  geom_histogram(aes(data_jit, y=..density..))+
  ggtitle("Histogram of the jittered data")+
  xlab("Diameters")+
  ylab("")+
  geom_line(aes(seq, f(seq, opti[1], opti[2], opti[3], opti[4],opti[5]), colour="Density_Optimized"))+
  geom_line(aes(seq, f(seq, mu1, mu2, sigma1, sigma2, tau), colour="Density_Obtained"))+
  scale_color_manual(name="", values=c(Density_Optimized = "palegreen3", Density_Obtained="hotpink2"))+
    geom_line(aes(x[1:51], data$value[1:51]/length_inter[1:51]), color="black")

```


## Parametric Bootstrap 


```{r, Evaluation of the T statistic, eval=FALSE }
#cumulative funnction of the mixture law
pl <- function(x, mu1, mu2, sigma1, sigma2, tau){
  return(tau * plnorm(x, mu2, sigma2) + (1-tau)*plnorm(x, mu1, sigma1))
}

# Calcul of the statistic 

ecdd <- ecdf(X)
ecd <- ecdd(sort(X))
tt <- max(abs(ecd-pl(sort(X), opti[1], opti[2], opti[3], opti[4], opti[5])))
```


```{r, bootstrap, eval=FALSE}
B <- 100
opt <- matrix(0, nrow=B, ncol=5)
t <- rep(0, B)

for (b in 1:B){
  # 1) Génération du sample & data
  samp <- sample(x=1:52, size=data$number[1], prob=data$value, replace=TRUE)
  vec = rep(0, 52)
  for (i in 1:52){
    vec[i] <- sum(samp==i)
  }
    
  vect = vec / data$number[1]* 100
    
  data2 <- data.frame(startpoint <- data$startpoint,
                        endpoint <- data$endpoint,
                        value <- vect,
                        number <- data$number)
  
  # 2) Jittered data 
  number <- round((data2$value * data2$number)/100)
  data_jit <- rep(0, length(number))
  k <- 0
  for(i in 1:45){
    data_jit[(k+1) : (k + number[i])] <- runif(number[i], data2$startpoint[i], data2$endpoint[i])
    k <- k + number[i]
  }
  
  X <- data_jit
  
  # 3) Fonction EM 
  L <- em(X, 0.000001, opti[1], opti[2] ,opti[3],  opti[4], opti[5])
    
  mu1 = unlist(L[1])
  mu2 = unlist(L[2])
  sigma1 = unlist(L[3])
  sigma2 = unlist(L[4])
  tau = unlist(L[5])
  
  # 4) Optimisation 
  opt[b, 1:5] <- optim(par=c(mu1, mu2, sigma1, sigma2, tau), log_round, data=data2)$par
  
  # 5) 
  #seq <- seq(0, 1.5, 0.1)
  ecdd <- ecdf(X)
  ecd <- ecdd(sort(X))
  t[b] <- max(abs(ecd-pl(sort(X), opt[b, 1], opt[b, 2], opt[b, 3], opt[b, 4], opt[b, 5])))
}

p_value <- (1+ sum(t > tt))/(B+1)

```






